apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: arch-analyzer-api

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
  - configmap.yaml
  - aws-secret-template.yaml

commonLabels:
  app.kubernetes.io/part-of: arch-analyzer

images:
  - name: arch-analyzer-gateway
    newName: ${ECR_REGISTRY}/arch-analyzer-gateway
    newTag: ${IMAGE_TAG}
