apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: arch-analyzer-api
  labels:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/part-of: arch-analyzer
    app.kubernetes.io/component: gateway
spec:
  type: ClusterIP
  selector:
    app: api-gateway
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
