name: CI Release

on:
  push:
    branches:
      - "release/*"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@5579c002bb4778aa43395ef1df492868a9a1c83f # v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2

      - name: Terraform Init
        run: terraform init
        working-directory: ./infra/terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./infra/terraform

      - name: Terraform Plan
        run: terraform plan -var="aws_region=us-east-1"
        working-directory: ./infra/terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

  create-pr-to-main:
    needs: [build-and-test]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout do código completo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Criar Pull Request para Main
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          sudo apt-get update && sudo apt-get install -y jq
          set -e

          TARGET_BRANCH="main"
          SOURCE_BRANCH="${{ github.ref_name }}"

          echo "🔍 Verificando se há diferenças entre $SOURCE_BRANCH e $TARGET_BRANCH..."
          git fetch origin "$TARGET_BRANCH"
          if git diff --quiet "origin/$TARGET_BRANCH"...origin/"$SOURCE_BRANCH"; then
            echo "⚠️ Nenhuma diferença. Nenhum PR será criado."
            exit 0
          fi

          echo "🔍 Verificando PRs abertos..."
          PR_LIST=$(gh pr list --state open --head "$SOURCE_BRANCH" --base "$TARGET_BRANCH" --json number)
          OPEN_PR_COUNT=$(echo "$PR_LIST" | jq 'length')

          if [ -z "$OPEN_PR_COUNT" ] || [ "$OPEN_PR_COUNT" -eq 0 ]; then
            echo "✨ Criando novo Pull Request para $TARGET_BRANCH..."
            gh pr create \
              --base "$TARGET_BRANCH" \
              --head "$SOURCE_BRANCH" \
              --title "Merge $SOURCE_BRANCH into $TARGET_BRANCH" \
              --body "PR gerado automaticamente após sucesso no CI da release."
          else
            echo "ℹ️ Já existe PR aberto."
          fi
